job_id=EDARSAHUB-ISCAM-EXECUTIVE-SOURCE-OF-TRUTH-R2-CARLOS-20260904T230300Z
requested_by=carlosruz@edarsa.com.mx
request_source=chatgpt
project=V1
production_allowed=false
base_commit=8da36dfd917a54ca608272f45094e247e25541a3
reason=STRICT PRECONDITION / FAIL-CLOSED: the Dashboard Ejecutivo is the source-of-truth contract for every sales report. Do not invent, copy, approximate, or independently reimplement sales-period logic in ISCAM. Before changing application code, prove from the current branch that Dashboard Ejecutivo /api/dashboard-ejecutivo/resumen uses core.kpis_canonicos.KPIsCanonicosService.resumen_periodo_desglosado and publishes its primary kpis/ventas_por_unidad from desglose['acumulado_cerrado'], with contrato_acumulado='CERRADO_SIN_DIA_OPERATIVO_ACTUAL'. Confirm the shared canonical service defines acumulado_cerrado by resumen_periodo(..., corte_dia_operativo='excluir'), dia_actual separately by 'solo', and total_incluyendo_dia only as informational 'incluir'. Confirm SoftRestaurant canonical closed-sales ingestion is still QUERY_SOFTRESTAURANT_VENTAS_CERRADAS_DIA/build_softrestaurant_ventas_cerradas_query using turnos.apertura for operational-period assignment, turnos.cierre IS NOT NULL only as closed-turn eligibility, canonical idempresa, configured operational window, and cheques.cancelado=0. ONLY IF all of those contracts are true and can be reused unchanged, proceed. Otherwise STOP with BLOCKED_CONTRACT_MISMATCH and make no application-code/data changes.

If precondition passes, correct ISCAM so /inteligencia/iscam/ventas-periodos is based on the EXACT SAME shared KPIsCanonicosService contract as Dashboard Ejecutivo, not a direct SUM over vw_Comercial_KPIs_Diarios_v2_Runtime and not Sync_Sales. For each requested day/month/year bucket, obtain the sales result through the shared canonical service and use only acumulado_cerrado as the reported closed sales. Do not include dia_actual/open-turn overlay in the closed period amount. If the current operational day needs display, expose it separately and label it as current/open operation, never mix it into the closed monthly total. Metrics must match Executive definitions exactly: ventas principal = canonical ventas_total with IVA; propinas separate; cheques/tickets canonical; pax canonical; cheque_promedio = ventas/cheques; pax/consumo_promedio = ventas/pax. Do not modify Dashboard Ejecutivo behavior.

Month/date attribution must also be identical to Executive ingestion: SoftRestaurant sales are attributed by the operational date derived from turnos.apertura, never by cierre timestamp. A prior operational turn that closes later must, after canonical resync, remain attributed to the original apertura operational date/month. Example for regression semantics only: a turn opened in the Aug-31 operational window and closed Sep-01 belongs to August after it closes; while open it must not inflate August or September closed sales. Add regression tests for this month-boundary case and for open-day exclusion.

The previously requested 'Sincronizar vista' button may be implemented ONLY by delegating to the same canonical resync handler that feeds Dashboard Ejecutivo; it must not contain report-specific business SQL. Use selected unidad + visible date range, preserve RBAC, run dry-run first, then real resync only when dry-run succeeds, reconcile canonical detail after successful header sync, refresh the view, and fail closed on any mismatch. Do not touch Production.

Acceptance gate before declaring success: for identical unidad/date filters, compare Dashboard Ejecutivo accumulated_cerrado vs ISCAM Ventas por Periodo at day/month/year levels. ventas, propinas, cheques and pax must be exactly equal; derived averages must be equal within normal decimal rounding. For ESTELAR 2026-09-01 also reconcile the source read-only and the official SoftRestaurant report evidence already provided by Carlos, but do not hardcode business totals. Return evidence of precondition proof, before/after discrepancies, source lineage, exact files changed, tests/build, runtime validation, resulting Edarsahub_Desarrollo SHA, quality gate and status. If exact Executive parity cannot be demonstrated, report BLOCKED and do not publish a functional change.