"""
Reglas base EDARSAHUB Hospitality.
No contiene lógica operativa todavía.
"""

HOSPITALITY_MAXIMAS = [
    "NO_ROMPER",
    "NO_MONGO",
    "NO_LIVE_OPERATIVO",
    "SQL_FIRST",
    "NO_DUPLICAR",
    "UNIDAD_NEGOCIO_PK",
    "RBAC_EXISTENTE",
    "FILTROS_CORPORATIVOS",
    "SCHEDULER_EXISTENTE",
    "NOTIFICACIONES_EXISTENTES",
    "COMANDERO_EXISTENTE",
    "MULTIDIOMA_GLOBAL",
    "MULTICONECTIVIDAD",
    "AUTOMATIZACION_SEGURA",
]
