import hashlib,json,os
from datetime import date,timedelta
from pathlib import Path
import pymssql,pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from core.rbac_helper_sql import NIVEL_ACCESO_TOTAL
from core.security import create_token
from modules.catalogo_ampliado.routes import router
pytestmark=pytest.mark.skipif(os.environ.get('CATALOGO_GATE6_REAL')!='1',reason='real Gate6 only')
def db(): return pymssql.connect(server=os.environ['EDARSAHUB_SQL_HOST'],port=int(os.environ['EDARSAHUB_SQL_PORT']),database=os.environ['EDARSAHUB_SQL_DATABASE'],user=os.environ['EDARSAHUB_SQL_USER'],password=os.environ['EDARSAHUB_SQL_PASSWORD'],timeout=60,login_timeout=15)
def call(c,m,p,t=None,b=None): return c.request(m,p,headers={'Authorization':'Bearer '+t} if t else {},json=b)
def test_gate6_real():
 mark='G6E2E-'+os.environ.get('GITHUB_RUN_ID','local'); out=Path(os.environ['GATE6_EVIDENCE_FILE']); ev={'status':'FAIL','checks':{},'cleanup':{},'production_touched':False}; ids={k:None for k in ('tipo','persona','vinculo','doc','ver','alerta')}; emp=None; before=None; con=db(); q=con.cursor(as_dict=True); failure=None
 try:
  q.execute('SELECT TOP 1 uc.UsuarioID,uc.Email,ur.CodigoRol FROM dbo.Usuario_Catalogo uc JOIN dbo.Usuario_RolesAsignacion a ON a.UsuarioID=uc.UsuarioID AND ISNULL(a.Activo,1)=1 AND ISNULL(a.EsPrincipal,0)=1 JOIN dbo.Usuario_Roles ur ON ur.RolID=a.RolID AND ISNULL(ur.Activo,1)=1 WHERE ISNULL(uc.Activo,1)=1 AND ur.NivelJerarquia >= %s AND uc.Email IS NOT NULL ORDER BY ur.NivelJerarquia DESC,uc.UsuarioID',(NIVEL_ACCESO_TOTAL,)); full=q.fetchone(); q.execute('SELECT TOP 1 uc.UsuarioID,uc.Email,ur.CodigoRol FROM dbo.Usuario_Catalogo uc JOIN dbo.Usuario_RolesAsignacion a ON a.UsuarioID=uc.UsuarioID AND ISNULL(a.Activo,1)=1 AND ISNULL(a.EsPrincipal,0)=1 JOIN dbo.Usuario_Roles ur ON ur.RolID=a.RolID AND ISNULL(ur.Activo,1)=1 WHERE ISNULL(uc.Activo,1)=1 AND ur.NivelJerarquia < %s AND uc.Email IS NOT NULL ORDER BY ur.NivelJerarquia,uc.UsuarioID',(NIVEL_ACCESO_TOTAL,)); low=q.fetchone(); q.execute('SELECT TOP 1 uc.UsuarioID FROM dbo.Usuario_Catalogo uc LEFT JOIN dbo.Gobierno_PersonaVinculo pv ON pv.UsuarioID=uc.UsuarioID WHERE ISNULL(uc.Activo,1)=1 AND pv.VinculoID IS NULL ORDER BY uc.UsuarioID'); link=q.fetchone(); q.execute('SELECT TOP 1 EmpresaID FROM dbo.Sistema_Empresas ORDER BY EmpresaID'); er=q.fetchone(); assert full and low and link and er,'CANONICAL_FIXTURE_MISSING'; emp=int(er['EmpresaID']); q.execute('SELECT * FROM dbo.Gobierno_EmpresaConfiguracion WHERE EmpresaID=%s',(emp,)); before=q.fetchone(); q.execute("INSERT INTO dbo.Gobierno_TipoDocumento(Codigo,Nombre,PropietarioPermitido,RequiereVigencia,Sensibilidad) OUTPUT INSERTED.TipoDocumentoID VALUES(%s,%s,'EMPRESA',1,'RESTRINGIDO')",(mark,mark)); ids['tipo']=int(q.fetchone()['TipoDocumentoID']); con.commit()
  app=FastAPI(); app.include_router(router,prefix='/api'); c=TestClient(app); hi=create_token(str(full['UsuarioID']),full['Email'],full['CodigoRol']); lo=create_token(str(low['UsuarioID']),low['Email'],low['CodigoRol']); base='/api/catalogo-ampliado'; ev['checks']['auth_missing']=call(c,'GET',base+'/empresas/'+str(emp)+'/configuracion').status_code in (401,403); ev['checks']['auth_invalid']=call(c,'GET',base+'/empresas/'+str(emp)+'/configuracion','invalid').status_code==401; ev['checks']['rbac_deny']=call(c,'GET',base+'/empresas/'+str(emp)+'/configuracion',lo).status_code==403; ev['checks']['rbac_allow']=call(c,'GET',base+'/empresas/'+str(emp)+'/configuracion',hi).status_code==200
  assert call(c,'PUT',base+'/empresas/'+str(emp)+'/configuracion',hi,{'catalogo_legal_ampliado_activo':False,'dias_alerta_default':30}).status_code==200; ev['checks']['activation_fail_closed']=call(c,'GET',base+'/empresas/'+str(emp)+'/documentos',hi).status_code==409; assert call(c,'PUT',base+'/empresas/'+str(emp)+'/configuracion',hi,{'catalogo_legal_ampliado_activo':True,'dias_alerta_default':30}).status_code==200
  r=call(c,'POST',base+'/personas',hi,{'nombre':mark}); assert r.status_code==201,r.text; ids['persona']=int(r.json()['data']['PersonaID']); r=call(c,'POST',base+'/personas/'+str(ids['persona'])+'/vinculos',hi,{'usuario_id':int(link['UsuarioID']),'cliente_id':None,'proveedor_id':None,'contacto_cliente_id':None,'contacto_proveedor_id':None,'es_principal':True}); assert r.status_code==201,r.text; ids['vinculo']=int(r.json()['data']['VinculoID']); ev['checks']['persona_vinculo']=True
  r=call(c,'POST',base+'/empresas/'+str(emp)+'/documentos',hi,{'tipo_documento_id':ids['tipo'],'propietario_tipo':'EMPRESA','titulo':mark}); assert r.status_code==201,r.text; ids['doc']=int(r.json()['data']['DocumentoID']); today=date.today(); exp=today+timedelta(days=30); sha=hashlib.sha256(mark.encode()).hexdigest(); r=call(c,'POST',base+'/documentos/'+str(ids['doc'])+'/versiones',hi,{'nombre_archivo':mark+'.pdf','storage_key':'e2e/'+mark+'.pdf','mime_type':'application/pdf','tamanio_bytes':123,'sha256':sha,'fecha_emision':str(today),'fecha_vencimiento':str(exp),'fecha_vencimiento_fuente':'CAPTURA'}); assert r.status_code==201,r.text; ids['ver']=int(r.json()['data']['DocumentoVersionID']); r=call(c,'GET',base+'/documentos/'+str(ids['doc'])+'/kardex',hi); assert r.status_code==200,r.text; ev['checks']['kardex']={'CREACION','NUEVA_VERSION'}.issubset({x['TipoMovimiento'] for x in r.json()['data']})
  q.execute("UPDATE dbo.Gobierno_DocumentoVersion SET EstadoRevision='VALIDADO',RevisadoPorUsuarioID=%s,FechaRevision=SYSUTCDATETIME() WHERE DocumentoVersionID=%s",(int(full['UsuarioID']),ids['ver'])); con.commit(); r=call(c,'GET',base+'/empresas/'+str(emp)+'/vencimientos?dias=60',hi); assert r.status_code==200,r.text; ev['checks']['vencimiento']=any(int(x['DocumentoVersionID'])==ids['ver'] for x in r.json()['data']); r=call(c,'POST',base+'/empresas/'+str(emp)+'/alertas/reglas',hi,{'tipo_documento_id':ids['tipo'],'usuario_objetivo_id':int(full['UsuarioID']),'dias_antes':30,'canal':'APP'}); assert r.status_code==201,r.text; ids['alerta']=int(r.json()['data']['AlertaReglaID']); r=call(c,'GET',base+'/empresas/'+str(emp)+'/alertas/reglas',hi); assert r.status_code==200,r.text; ev['checks']['alerta']=any(int(x['AlertaReglaID'])==ids['alerta'] for x in r.json()['data']); assert all(ev['checks'].values()),ev['checks']; ev['status']='PASS'
 except Exception as x: failure=x; ev['error']=type(x).__name__+': '+str(x)[:500]
 finally:
  try:
   if ids['alerta']: q.execute('DELETE FROM dbo.Gobierno_AlertaRegla WHERE AlertaReglaID=%s',(ids['alerta'],))
   if ids['doc']: q.execute('DELETE FROM dbo.Gobierno_DocumentoMovimiento WHERE DocumentoID=%s',(ids['doc'],)); q.execute('DELETE FROM dbo.Gobierno_DocumentoVersion WHERE DocumentoID=%s',(ids['doc'],)); q.execute('DELETE FROM dbo.Gobierno_Documento WHERE DocumentoID=%s',(ids['doc'],))
   if ids['vinculo']: q.execute('DELETE FROM dbo.Gobierno_PersonaVinculo WHERE VinculoID=%s',(ids['vinculo'],))
   if ids['persona']: q.execute('DELETE FROM dbo.Gobierno_Persona WHERE PersonaID=%s',(ids['persona'],))
   if ids['tipo']: q.execute('DELETE FROM dbo.Gobierno_TipoDocumento WHERE TipoDocumentoID=%s',(ids['tipo'],))
   if emp is not None:
    if before: q.execute('UPDATE dbo.Gobierno_EmpresaConfiguracion SET CatalogoLegalAmpliadoActivo=%s,DiasAlertaDefault=%s,Activo=%s,FechaActualizacion=%s,UsuarioActualizacionID=%s WHERE EmpresaID=%s',(before['CatalogoLegalAmpliadoActivo'],before['DiasAlertaDefault'],before['Activo'],before['FechaActualizacion'],before['UsuarioActualizacionID'],emp))
    else: q.execute('DELETE FROM dbo.Gobierno_EmpresaConfiguracion WHERE EmpresaID=%s',(emp,))
   con.commit(); q.execute('SELECT (SELECT COUNT_BIG(*) FROM dbo.Gobierno_Persona WHERE Nombre=%s)+(SELECT COUNT_BIG(*) FROM dbo.Gobierno_TipoDocumento WHERE Codigo=%s)+(SELECT COUNT_BIG(*) FROM dbo.Gobierno_Documento WHERE Titulo=%s) residue',(mark,mark,mark)); residue=int(q.fetchone()['residue']); ev['cleanup']={'complete':residue==0,'residue':residue}; ev['status']='FAIL' if residue else ev['status']
  except Exception as cx: con.rollback(); ev['cleanup']={'complete':False,'error':str(cx)[:500]}; ev['status']='FAIL'
  out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(ev,indent=2,sort_keys=True,default=str),encoding='utf-8'); q.close(); con.close()
 if failure: raise failure
 assert ev['status']=='PASS' and ev['cleanup']['complete'] and ev['cleanup']['residue']==0
