"""Contrato único de campos del ticket; fuente persistida, sin consultas LIVE."""
from __future__ import annotations

FIELD_TYPES = {'partida_origen_id': 'nvarchar(100)',
 'partida_key': 'nvarchar(100)',
 'cliente_id': 'nvarchar(100)',
 'cliente_nombre': 'nvarchar(max)',
 'cliente_razon_social': 'nvarchar(max)',
 'cliente_descripcion': 'nvarchar(max)',
 'cliente_maestro_id': 'nvarchar(100)',
 'cliente_sucursal_origen': 'nvarchar(50)',
 'cliente_contacto': 'nvarchar(max)',
 'cliente_rfc': 'nvarchar(50)',
 'cliente_direccion_1': 'nvarchar(max)',
 'cliente_direccion_2': 'nvarchar(max)',
 'cliente_direccion_3': 'nvarchar(max)',
 'cliente_calle': 'nvarchar(max)',
 'cliente_numero_exterior': 'nvarchar(max)',
 'cliente_numero_interior': 'nvarchar(max)',
 'cliente_colonia': 'nvarchar(max)',
 'cliente_ciudad': 'nvarchar(max)',
 'cliente_municipio': 'nvarchar(max)',
 'cliente_estado': 'nvarchar(max)',
 'cliente_pais': 'nvarchar(max)',
 'cliente_codigo_postal': 'nvarchar(max)',
 'ticket_fecha': 'datetime2',
 'ticket_fecha_cierre': 'datetime2',
 'ticket_pagado': 'bit',
 'ticket_impreso': 'bit',
 'ticket_impresiones': 'int',
 'ticket_comentario': 'nvarchar(max)',
 'ticket_comentario_descuento': 'nvarchar(max)',
 'ticket_fecha_alta': 'datetime2',
 'ticket_oper_ult_modif': 'nvarchar(100)',
 'ticket_oper_baja': 'nvarchar(100)',
 'ticket_fecha_baja': 'datetime2',
 'partida_comentario': 'nvarchar(max)',
 'partida_comentario_descuento': 'nvarchar(max)',
 'partida_comentario_cancelacion': 'nvarchar(max)',
 'partida_oper_baja': 'nvarchar(100)',
 'partida_fecha_baja': 'datetime2',
 'tipo_descuento_id': 'nvarchar(100)',
 'tipo_descuento_descripcion': 'nvarchar(max)',
 'tipo_descuento_valor': 'decimal(18,6)',
 'cliente_cruzamiento_1': 'nvarchar(max)',
 'cliente_cruzamiento_2': 'nvarchar(max)',
 'cliente_entrega_direccion_1': 'nvarchar(max)',
 'cliente_entrega_direccion_2': 'nvarchar(max)',
 'cliente_entrega_direccion_3': 'nvarchar(max)',
 'cliente_entrega_ciudad': 'nvarchar(max)',
 'cliente_entrega_estado': 'nvarchar(max)',
 'cliente_entrega_pais': 'nvarchar(max)',
 'cliente_entrega_codigo_postal': 'nvarchar(max)',
 'cliente_colonia_origen_id': 'nvarchar(max)',
 'cliente_ciudad_origen_id': 'nvarchar(max)',
 'cliente_municipio_origen_id': 'nvarchar(max)',
 'cliente_estado_origen_id': 'nvarchar(max)',
 'cliente_pais_origen_id': 'nvarchar(max)',
 'cliente_codigo_postal_origen_id': 'nvarchar(max)',
 'cliente_latitud': 'nvarchar(max)',
 'cliente_longitud': 'nvarchar(max)'}
FIELDS = tuple(FIELD_TYPES)

def fields_from(row):
    return {field: row.get(field) for field in FIELDS}


def discount_comment(row):
    # El catálogo tiene prioridad para presentación; el comentario original se conserva.
    if row.get('tipo_descuento_id') and row.get('tipo_descuento_descripcion'):
        return row['tipo_descuento_descripcion']
    return row.get('partida_comentario_descuento')


def header_from(rows):
    result = {}
    for field in FIELDS:
        if field.startswith(('cliente_', 'ticket_')):
            values = [r.get(field) for r in rows if r.get(field) not in (None, '')]
            # Nunca escoger silenciosamente entre clientes diferentes del mismo ticket.
            if len({str(v) for v in values}) > 1:
                raise ValueError('TICKET_HEADER_CONFLICT:' + field)
            result[field] = values[0] if values else None
    parts = [result.get('cliente_'+k) for k in (
        'direccion_1','direccion_2','direccion_3','calle','numero_exterior',
        'numero_interior','cruzamiento_1','cruzamiento_2','colonia','municipio','ciudad','estado','pais','codigo_postal')]
    seen = set()
    address = []
    for value in parts:
        value = str(value or '').strip()
        if value and value.casefold() not in seen:
            address.append(value)
            seen.add(value.casefold())
    result['cliente_direccion'] = ', '.join(address) or None
    return result

SR_EXPRESSIONS = {'partida_origen_id': 'CONVERT(nvarchar(100), d.movimiento)',
 'partida_key': 'NULL',
 'cliente_id': 'h.idcliente',
 'cliente_nombre': 'cl.nombre',
 'cliente_razon_social': 'NULL',
 'cliente_descripcion': 'NULL',
 'cliente_maestro_id': 'NULL',
 'cliente_sucursal_origen': 'NULL',
 'cliente_contacto': 'cl.contacto',
 'cliente_rfc': 'cl.rfc',
 'cliente_direccion_1': 'cl.direccion',
 'cliente_direccion_2': 'NULL',
 'cliente_direccion_3': 'NULL',
 'cliente_calle': 'NULL',
 'cliente_numero_exterior': 'NULL',
 'cliente_numero_interior': 'NULL',
 'cliente_colonia': 'NULL',
 'cliente_ciudad': 'cl.poblacion',
 'cliente_municipio': 'NULL',
 'cliente_estado': 'cl.estado',
 'cliente_pais': 'cl.pais',
 'cliente_codigo_postal': 'cl.codigopostal',
 'ticket_fecha': 'h.fecha',
 'ticket_fecha_cierre': 'h.cierre',
 'ticket_pagado': 'h.pagado',
 'ticket_impreso': 'h.impreso',
 'ticket_impresiones': 'h.impresiones',
 'ticket_comentario': 'NULL',
 'ticket_comentario_descuento': 'h.comentariodescuento',
 'ticket_fecha_alta': 'NULL',
 'ticket_oper_ult_modif': 'NULL',
 'ticket_oper_baja': 'NULL',
 'ticket_fecha_baja': 'h.fechacancelado',
 'partida_comentario': 'd.comentario',
 'partida_comentario_descuento': 'd.comentariodescuento',
 'partida_comentario_cancelacion': 'NULL',
 'partida_oper_baja': 'NULL',
 'partida_fecha_baja': 'NULL',
 'tipo_descuento_id': 'd.idtipodescuento',
 'tipo_descuento_descripcion': 'td.desc_tipodescuento',
 'tipo_descuento_valor': 'td.descuento',
 'cliente_cruzamiento_1': 'NULL',
 'cliente_cruzamiento_2': 'NULL',
 'cliente_entrega_direccion_1': 'NULL',
 'cliente_entrega_direccion_2': 'NULL',
 'cliente_entrega_direccion_3': 'NULL',
 'cliente_entrega_ciudad': 'NULL',
 'cliente_entrega_estado': 'NULL',
 'cliente_entrega_pais': 'NULL',
 'cliente_entrega_codigo_postal': 'NULL',
 'cliente_colonia_origen_id': 'NULL',
 'cliente_ciudad_origen_id': 'NULL',
 'cliente_municipio_origen_id': 'NULL',
 'cliente_estado_origen_id': 'NULL',
 'cliente_pais_origen_id': 'NULL',
 'cliente_codigo_postal_origen_id': 'NULL',
 'cliente_latitud': 'NULL',
 'cliente_longitud': 'NULL'}
MPRO_EXPRESSIONS = {'partida_origen_id': 'CONVERT(nvarchar(100), d.Cd_Id)',
 'partida_key': 'd.Cd_Key',
 'cliente_id': 'h.Cl_Cve_Cliente',
 'cliente_nombre': "COALESCE(NULLIF(cl.Cl_Razon_Social,''),NULLIF(cl.Cl_Descripcion,''))",
 'cliente_razon_social': 'cl.Cl_Razon_Social',
 'cliente_descripcion': 'cl.Cl_Descripcion',
 'cliente_maestro_id': 'cl.Cl_Cve_Maestro',
 'cliente_sucursal_origen': 'cl.Sc_Cve_Sucursal',
 'cliente_contacto': 'cl.Cl_Contacto_1',
 'cliente_rfc': 'cl.Cl_R_F_C',
 'cliente_direccion_1': 'cl.Cl_Direccion_1',
 'cliente_direccion_2': 'cl.Cl_Direccion_2',
 'cliente_direccion_3': 'cl.Cl_Direccion_3',
 'cliente_calle': 'cl.Cl_Calle',
 'cliente_numero_exterior': 'cl.Cl_Numero_Exterior',
 'cliente_numero_interior': 'cl.Cl_Numero_Interior',
 'cliente_colonia': 'cl.Cl_Colonia',
 'cliente_ciudad': 'cl.Cl_Ciudad',
 'cliente_municipio': 'cl.Cl_Municipio',
 'cliente_estado': 'cl.Cl_Estado',
 'cliente_pais': 'cl.Cl_Pais',
 'cliente_codigo_postal': 'cl.Cl_Codigo_Postal',
 'ticket_fecha': 'h.Co_Fecha',
 'ticket_fecha_cierre': 'NULL',
 'ticket_pagado': 'NULL',
 'ticket_impreso': 'NULL',
 'ticket_impresiones': 'NULL',
 'ticket_comentario': 'h.Co_Comentario',
 'ticket_comentario_descuento': 'NULL',
 'ticket_fecha_alta': 'h.Fecha_Alta',
 'ticket_oper_ult_modif': 'h.Oper_Ult_Modif',
 'ticket_oper_baja': 'h.Oper_Baja',
 'ticket_fecha_baja': 'h.Fecha_Baja',
 'partida_comentario': 'd.Cd_Comentario',
 'partida_comentario_descuento': 'NULL',
 'partida_comentario_cancelacion': 'd.Cd_Comentario_Cancelacion',
 'partida_oper_baja': 'd.Oper_Baja',
 'partida_fecha_baja': 'd.Fecha_Baja',
 'tipo_descuento_id': 'd.Cd_Tipo_Descuento',
 'tipo_descuento_descripcion': 'td.Td_Descripcion',
 'tipo_descuento_valor': 'td.Td_Porcentaje',
 'cliente_cruzamiento_1': 'cl.Cl_Cruzamiento_1',
 'cliente_cruzamiento_2': 'cl.Cl_Cruzamiento_2',
 'cliente_entrega_direccion_1': 'cl.Cl_Direccion_Entrega_1',
 'cliente_entrega_direccion_2': 'cl.Cl_Direccion_Entrega_2',
 'cliente_entrega_direccion_3': 'cl.Cl_Direccion_Entrega_3',
 'cliente_entrega_ciudad': 'cl.Cl_Ciudad_Entrega',
 'cliente_entrega_estado': 'cl.Cl_Estado_Entrega',
 'cliente_entrega_pais': 'cl.Cl_Pais_Entrega',
 'cliente_entrega_codigo_postal': 'cl.Cl_Codigo_Postal_Entrega',
 'cliente_colonia_origen_id': 'cl.Cl_Cve_Colonia',
 'cliente_ciudad_origen_id': 'cl.Cl_Cve_Ciudad',
 'cliente_municipio_origen_id': 'cl.Cl_Cve_Municipio',
 'cliente_estado_origen_id': 'cl.Cl_Cve_Estado',
 'cliente_pais_origen_id': 'cl.Cl_Cve_Pais',
 'cliente_codigo_postal_origen_id': 'cl.Cl_Cve_Codigo_Postal',
 'cliente_latitud': 'cl.Cl_Latitud',
 'cliente_longitud': 'cl.Cl_Longitud'}
