-- ActivoFijo_ClaseActivo - 8 registros
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (1, N'MINISPLIT', N'Equipo de aire acondicionado tipo minisplit', 1, 1, 1, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (2, N'PAQUETE HVAC', N'Unidad paquete HVAC', 1, 1, 1, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (3, N'CAMARA FRIA', N'Equipo de refrigeración / cuarto frío', 2, 1, 1, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (4, N'REFRIGERADOR COMERCIAL', N'Refrigerador de operación', 2, 1, 1, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (5, N'EQUIPO DE COCINA', N'Activo de cocina', 3, 1, 0, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (6, N'MOBILIARIO', N'Mesas, sillas, anaqueles', 5, 1, 0, 1, 0, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (7, N'EQUIPO DE COMPUTO', N'PC, impresoras, tablets', 6, 1, 1, 1, 1, 1, 1);
INSERT INTO [ActivoFijo_ClaseActivo] ([ClaseActivoID], [Nombre], [Descripcion], [TipoActivoID], [Capitalizable], [RequiereSerie], [RequiereEtiqueta], [RequiereMantenimiento], [RequiereDepreciacion], [Activo]) VALUES (8, N'OTRO', N'Otros activos fijos', 9, 1, 0, 1, 0, 1, 1);
