-- ActivoFijo_ReglasClaseLibro - 9 registros
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (1, 1, 1, 1, 120, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (2, 1, 2, 1, 120, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (3, 2, 1, 1, 120, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (4, 3, 1, 1, 120, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (5, 4, 1, 1, 96, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (6, 5, 1, 1, 84, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (7, 6, 1, 1, 60, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (8, 7, 1, 1, 48, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
INSERT INTO [ActivoFijo_ReglasClaseLibro] ([ReglaClaseLibroID], [ClaseActivoID], [LibroDepreciacionID], [MetodoDepreciacionID], [VidaUtilMeses], [PorcentajeResidual], [Capitalizable], [Deprecia], [CuentaActivo], [CuentaDepreciacionAcum], [CuentaGastoDepreciacion], [CuentaBaja], [Activo]) VALUES (9, 8, 1, 1, 60, 5.0000, 1, 1, NULL, NULL, NULL, NULL, 1);
