-- Finanzas_ConfiguracionTPV_Sucursal - 8 registros
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (1, 1, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (2, 2, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (3, 3, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (4, 4, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (5, 5, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (6, 6, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (7, 7, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
INSERT INTO [Finanzas_ConfiguracionTPV_Sucursal] ([ConfiguracionTPVID], [SucursalID], [ProveedorTPV], [ComisionDebito], [ComisionCredito], [ComisionAmex], [ComisionInternacional], [AplicaIVAComision], [PorcentajeIVA], [DiasDepositoDebito], [DiasDepositoCredito], [DiasDepositoAmex], [DiasDepositoInternacional], [DiasDepositoEfectivo], [EfectivoFinDeSemanaLunes], [CuentaBancariaID], [NumeroAfiliacion], [TerminalID], [Activo], [FechaAlta], [FechaModificacion]) VALUES (8, 8, N'NetPay', 1.200, 1.500, 2.400, 2.000, 1, 16.00, 1, 1, 2, 2, 1, 1, NULL, NULL, NULL, 1, N'2026-04-12T21:07:05.603333', NULL);
