-- RH_Cat_Departamentos - 11 registros
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (1, N'ADMINISTRACION', N'ADMINISTRACION', NULL, 1, N'2026-04-12T09:49:34.990432', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (2, N'AUDITORIA', N'AUDITORIA', NULL, 1, N'2026-04-12T09:49:35.147974', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (3, N'CAJAS', N'CAJAS', NULL, 1, N'2026-04-12T09:49:35.272987', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (4, N'CAPITAL HUMANO', N'CAPITAL HUMANO', NULL, 1, N'2026-04-12T09:49:35.398000', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (5, N'COCINA', N'COCINA', NULL, 1, N'2026-04-12T09:49:35.538642', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (6, N'CONTABILIDAD', N'CONTABILIDAD', NULL, 1, N'2026-04-12T09:49:35.662145', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (7, N'MARKETING', N'MARKETING', NULL, 1, N'2026-04-12T09:49:35.804008', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (8, N'OPERACIONES', N'OPERACIONES', NULL, 1, N'2026-04-12T09:49:35.930259', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (9, N'PISO', N'PISO', NULL, 1, N'2026-04-12T09:49:36.070902', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (10, N'TECNOLOGIAS DE LA IN', N'TECNOLOGIAS DE LA INFORMACION', NULL, 1, N'2026-04-12T09:49:36.245575', NULL);
INSERT INTO [RH_Cat_Departamentos] ([DepartamentoID], [CodigoDepartamento], [NombreDepartamento], [Descripcion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (11, N'TESORERIA', N'TESORERIA', NULL, 1, N'2026-04-12T09:49:36.370588', NULL);
