-- RH_Cat_ConceptosNomina - 10 registros
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (1, N'SUELDO', N'Sueldo ordinario', 1, N'001', NULL, 1, 0, 1, 1, 0, 1, 1, 0, 1, 10, 1, N'2026-04-09T12:02:27.280046', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (2, N'HORAS_EXTRA', N'Horas extra', 1, N'019', NULL, 1, 1, 1, 1, 0, 1, 1, 1, 1, 20, 1, N'2026-04-09T12:02:27.390636', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (3, N'VACACIONES', N'Vacaciones disfrutadas pagadas', 1, N'001', NULL, 1, 0, 1, 1, 0, 1, 1, 0, 1, 30, 1, N'2026-04-09T12:02:27.484430', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (4, N'PRIMA_VAC', N'Prima vacacional', 1, N'021', NULL, 1, 1, 1, 1, 0, 1, 1, 0, 0, 40, 1, N'2026-04-09T12:02:27.579455', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (5, N'AGUINALDO', N'Aguinaldo', 1, N'002', NULL, 1, 1, 0, 1, 0, 0, 0, 0, 0, 50, 1, N'2026-04-09T12:02:27.690035', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (6, N'ISR', N'ISR retenido', 2, N'002', NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 1, N'2026-04-09T12:02:27.783850', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (7, N'IMSS', N'Cuota IMSS trabajador', 2, N'001', NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 110, 1, N'2026-04-09T12:02:27.877610', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (8, N'INFONAVIT', N'Descuento Infonavit', 2, N'010', NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 1, N'2026-04-09T12:02:27.986997', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (9, N'PRESTAMO', N'Descuento préstamo empleado', 2, N'004', NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 1, N'2026-04-09T12:02:28.088867', NULL);
INSERT INTO [RH_Cat_ConceptosNomina] ([ConceptoNominaID], [CodigoConcepto], [NombreConcepto], [TipoConceptoNominaID], [ClaveSAT], [FormulaSQL], [EsGravado], [EsExento], [IntegraSBC], [AfectaISR], [AfectaSubsidio], [AfectaIMSS], [AfectaInfonavit], [EsEditableEnCaptura], [RequiereUnidades], [OrdenImpresion], [Activo], [FechaAlta], [FechaModificacion]) VALUES (10, N'SUBSIDIO', N'Subsidio al empleo', 3, N'002', NULL, 0, 0, 0, 0, 1, 0, 0, 0, 0, 140, 1, N'2026-04-09T12:02:28.187647', NULL);
