-- Sistema_ModulosPermisos - 13 registros
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (1, 1, N'comercial.perfil_unidad.ver', N'Ver Perfil Digital Unidad', N'Permite ver el perfil digital de la unidad de negocio', N'Pricing IA', 1, N'2026-05-24T22:56:32.913000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (2, 1, N'comercial.perfil_unidad.editar', N'Editar Perfil Digital Unidad', N'Permite editar el perfil digital de la unidad de negocio', N'Pricing IA', 1, N'2026-05-24T22:56:32.917000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (3, 1, N'comercial.competidores.ver', N'Ver Competidores', N'Permite ver el catálogo de competidores', N'Pricing IA', 1, N'2026-05-24T22:56:32.923000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (4, 1, N'comercial.competidores.crear', N'Crear Competidores', N'Permite agregar competidores al catálogo', N'Pricing IA', 1, N'2026-05-24T22:56:32.927000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (5, 1, N'comercial.competidores.editar', N'Editar Competidores', N'Permite editar competidores existentes', N'Pricing IA', 1, N'2026-05-24T22:56:32.937000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (6, 1, N'comercial.competidores.inactivar', N'Inactivar Competidores', N'Permite inactivar competidores', N'Pricing IA', 1, N'2026-05-24T22:56:32.937000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (7, 1, N'comercial.benchmark.ver', N'Ver Benchmark', N'Permite ver análisis de benchmark competitivo', N'Pricing IA', 1, N'2026-05-24T22:56:32.937000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (8, 1, N'comercial.benchmark.validar', N'Validar Benchmark', N'Permite validar comparables de benchmark', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (9, 1, N'comercial.benchmark.exportar', N'Exportar Benchmark', N'Permite exportar datos de benchmark', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (10, 1, N'comercial.precios_sugeridos.ver', N'Ver Precios Sugeridos', N'Permite ver precios sugeridos del menú', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (11, 1, N'comercial.precios_sugeridos.generar', N'Generar Precios Sugeridos', N'Permite generar cálculo de precios sugeridos', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (12, 1, N'comercial.precios_sugeridos.ver_ia', N'Ver Análisis IA', N'Permite ver justificaciones y análisis de IA', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
INSERT INTO [Sistema_ModulosPermisos] ([PermisoID], [ModuloID], [Codigo], [Nombre], [Descripcion], [Categoria], [Activo], [FechaCreacion]) VALUES (13, 1, N'comercial.precios_sugeridos.crear_solicitud', N'Crear Solicitud de Precio', N'Permite crear solicitud de cambio de precio desde precio sugerido', N'Pricing IA', 1, N'2026-05-24T22:56:32.940000');
