-- Sistema_ModulosVisibilidad - 16 registros
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (1, 1, N'EXPLORADOR_BD', N'Explorador de Base de Datos', 1, 10, NULL, 1, N'2026-05-15T21:59:51.480000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (2, 1, N'COMERCIAL', N'Dashboard Comercial', 1, 1, NULL, 1, N'2026-05-15T21:59:51.577000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (3, 1, N'COMPRAS', N'Módulo de Compras', 1, 3, NULL, 1, N'2026-05-15T21:59:51.673000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (4, 1, N'REPORTES', N'Reportes de Inventarios', 1, 5, NULL, 1, N'2026-05-15T21:59:51.770000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (5, 1, N'FINANZAS', N'Finanzas y Tesorería', 1, 4, NULL, 1, N'2026-05-15T21:59:51.867000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (6, 1, N'SYNC_HISTORICOS', N'Sincronización Histórica', 1, 20, NULL, 1, N'2026-05-15T21:59:51.960000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (7, 1, N'CATALOGO_SQL', N'Catálogo SQL', 1, 15, NULL, 1, N'2026-05-15T21:59:52.057000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (8, 2, N'EXPLORADOR_BD', N'Explorador de Base de Datos', 1, 10, NULL, 1, N'2026-05-15T21:59:52.153000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (9, 2, N'COMERCIAL', N'Dashboard Comercial', 1, 1, NULL, 1, N'2026-05-15T21:59:52.250000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (10, 2, N'COMPRAS', N'Módulo de Compras', 1, 3, NULL, 1, N'2026-05-15T21:59:52.347000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (11, 2, N'REPORTES', N'Reportes de Inventarios', 1, 5, NULL, 1, N'2026-05-15T21:59:52.443000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (12, 2, N'FINANZAS', N'Finanzas y Tesorería', 1, 4, NULL, 1, N'2026-05-15T21:59:52.540000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (13, 2, N'SYNC_HISTORICOS', N'Sincronización Histórica', 1, 20, NULL, 1, N'2026-05-15T21:59:52.637000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (14, 2, N'CATALOGO_SQL', N'Catálogo SQL', 1, 15, NULL, 1, N'2026-05-15T21:59:52.730000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (15, 3, N'EXPLORADOR_BD', N'Explorador de Base de Datos', 1, 10, NULL, 1, N'2026-05-15T21:59:52.827000');
INSERT INTO [Sistema_ModulosVisibilidad] ([ModuloVisibilidadID], [SistemaTipoID], [CodigoModulo], [DescripcionModulo], [Visible], [OrdenMenu], [ConfiguracionJSON], [Activo], [CreatedAt]) VALUES (16, 4, N'EXPLORADOR_BD', N'Explorador de Base de Datos', 1, 10, NULL, 1, N'2026-05-15T21:59:52.923000');
