-- Sistema_Migracion_MongoSQL_Mapeo - 8 registros
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('0aae9660-b755-420a-9c07-1123b15386e5', N'servers', N'Servidores_Conexiones', N'Sistema/Conexiones', N'PENDIENTE', N'P0', N'Migrar configuración de servidores a SQL; Mongo solo lectura temporal.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('0c190f97-bb1d-4631-a500-1ddc5fccc238', N'rbac_audit_log', NULL, N'RBAC/Auditoría', N'PENDIENTE', N'P1', N'Migrar a auditoría SQL transversal.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('4011d76c-3bf2-40ac-b3d2-4b79a743a7a7', N'empresas', N'Global_Cat_Empresas', N'Global', N'PENDIENTE', N'P0', N'Homologar empresas contra catálogo global SQL.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('dfaa43f4-7ffe-4f89-b9f0-55781e3f7cd1', N'rbac_permisos', NULL, N'RBAC', N'PENDIENTE', N'P0', N'Definir tablas SQL RBAC canónicas antes de migrar.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('cd226844-7e93-4b56-b1be-6f2da2e945ab', N'sucursales_catalogo', N'RH_Cat_Sucursales', N'Global/RH', N'PENDIENTE', N'P1', N'Validar si sucursal pertenece a RH o catálogo global operativo.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('59e2920d-d42a-4b1e-9237-9f7a4eed7a56', N'sucursal_servidor_map', N'Unidades_Negocio', N'Sistema/Unidades', N'PENDIENTE', N'P0', N'Unificar mapeo unidad-servidor en SQL.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('9263ad12-3807-4a45-8a29-a49b63a7a7ea', N'rbac_roles', NULL, N'RBAC', N'PENDIENTE', N'P0', N'Definir tablas SQL RBAC canónicas antes de migrar.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
INSERT INTO [Sistema_Migracion_MongoSQL_Mapeo] ([id], [coleccion_mongo], [tabla_sql_destino], [modulo], [estado], [prioridad], [estrategia], [fecha_inicio], [fecha_fin], [observaciones], [fecha_alta]) VALUES ('bab146db-deee-4ee9-896a-e5c6cb705022', N'rbac_usuarios_roles', NULL, N'RBAC', N'PENDIENTE', N'P0', N'Definir tablas SQL RBAC canónicas antes de migrar.', NULL, NULL, NULL, N'2026-06-02T03:47:24.747011');
