-- Sistema_EmpresasAlias - 12 registros
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (1, 1, N'ORIGEN', N'ORIGEN', N'CANONICO', 1, N'2026-05-15T02:46:45.380000', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (4, 2, N'130QRO', N'130QRO', N'CANONICO', 1, N'2026-05-15T02:46:45.476666', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (8, 2, N'130 QUERETARO', N'130QUERETARO', N'LEGACY', 1, N'2026-05-15T02:46:45.600000', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (10, 2, N'QUERETARO', N'QUERETARO', N'LEGACY', 1, N'2026-05-15T02:46:45.663333', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (11, 2, N'QRO', N'QRO', N'LEGACY', 1, N'2026-05-15T02:46:45.696666', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (12, 3, N'CIENFUEGOS', N'CIENFUEGOS', N'CANONICO', 1, N'2026-05-15T02:46:45.726666', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (14, 3, N'CF', N'CF', N'LEGACY', 1, N'2026-05-15T02:46:45.790000', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (15, 4, N'ESTELAR', N'ESTELAR', N'CANONICO', 1, N'2026-05-15T02:46:45.820000', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (16, 4, N'LA ESTELAR', N'LAESTELAR', N'LEGACY', 1, N'2026-05-15T02:46:45.853333', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (19, 5, N'130MID', N'130MID', N'CANONICO', 1, N'2026-05-15T02:46:45.946666', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (21, 5, N'130-MER', N'130MER', N'LEGACY', 1, N'2026-05-15T02:46:46.010000', NULL, N'DML_FASE_CATALOGO', NULL);
INSERT INTO [Sistema_EmpresasAlias] ([EmpresaAliasID], [EmpresaID], [Alias], [AliasNormalizado], [OrigenAlias], [Activo], [FechaCreacion], [FechaActualizacion], [CreatedBy], [UpdatedBy]) VALUES (23, 5, N'130 MERIDA', N'130MERIDA', N'LEGACY', 1, N'2026-05-15T02:46:46.070000', NULL, N'DML_FASE_CATALOGO', NULL);
