SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
 BEGIN TRANSACTION;
 DECLARE @now datetime2(3)=SYSUTCDATETIME();
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_provider_config' AND PayloadMongo LIKE '%"canal":"email"%' AND PayloadMongo LIKE '%"provider":"smtp"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:provider:catalogo-ampliado-email-smtp','notification_provider_config','{"id":"catalogo-ampliado-email-smtp","canal":"email","provider":"smtp","activo":true,"token_ref":"EMAIL_PASSWORD","metadata":{"source":"catalogo_ampliado_gate8f"}}',0,1,@now,@now);
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_provider_config' AND PayloadMongo LIKE '%"canal":"whatsapp"%' AND PayloadMongo LIKE '%"provider":"twilio"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:provider:catalogo-ampliado-whatsapp-twilio','notification_provider_config','{"id":"catalogo-ampliado-whatsapp-twilio","canal":"whatsapp","provider":"twilio","activo":true,"token_ref":"TWILIO_AUTH_TOKEN","metadata":{"source":"catalogo_ampliado_gate8f"}}',0,1,@now,@now);
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_templates' AND PayloadMongo LIKE '%"canal":"email"%' AND PayloadMongo LIKE '%"codigo":"catalogo_ampliado_documento_vencimiento"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:template:catalogo-ampliado-email-vencimiento','notification_templates','{"id":"catalogo-ampliado-email-vencimiento","canal":"email","codigo":"catalogo_ampliado_documento_vencimiento","nombre":"Documento por vencer","activo":true,"idioma":"es","template_texto":"EDARSA HUB: El documento {{titulo}} vence el {{fecha_objetivo}}. Ingresa al sistema para revisarlo.","variables":["titulo","fecha_objetivo"],"version":1}',0,1,@now,@now);
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_templates' AND PayloadMongo LIKE '%"canal":"whatsapp"%' AND PayloadMongo LIKE '%"codigo":"catalogo_ampliado_documento_vencimiento"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:template:catalogo-ampliado-whatsapp-vencimiento','notification_templates','{"id":"catalogo-ampliado-whatsapp-vencimiento","canal":"whatsapp","codigo":"catalogo_ampliado_documento_vencimiento","nombre":"Documento por vencer","activo":true,"idioma":"es","template_texto":"EDARSA HUB: El documento {{titulo}} vence el {{fecha_objetivo}}. Ingresa al sistema para revisarlo.","variables":["titulo","fecha_objetivo"],"version":1}',0,1,@now,@now);
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_config' AND PayloadMongo LIKE '%"modulo":"catalogo_ampliado"%' AND PayloadMongo LIKE '%"canal":"email"%' AND PayloadMongo LIKE '%"evento":"DOCUMENTO_VENCIMIENTO"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:config:catalogo-ampliado-email-vencimiento','notification_config','{"id":"catalogo-ampliado-email-vencimiento","canal":"email","modulo":"catalogo_ampliado","evento":"DOCUMENTO_VENCIMIENTO","activo":true,"provider":"smtp","modo_envio":"real","template_codigo":"catalogo_ampliado_documento_vencimiento","permite_reintentos":true,"max_reintentos":3,"ventana_duplicidad_minutos":1440}',0,1,@now,@now);
 IF NOT EXISTS (SELECT 1 FROM dbo.Sistema_NotificacionesConfig WHERE Activo=1 AND ColeccionOrigen='notification_config' AND PayloadMongo LIKE '%"modulo":"catalogo_ampliado"%' AND PayloadMongo LIKE '%"canal":"whatsapp"%' AND PayloadMongo LIKE '%"evento":"DOCUMENTO_VENCIMIENTO"%') INSERT INTO dbo.Sistema_NotificacionesConfig(Id,MongoId,ColeccionOrigen,PayloadMongo,MigradoDesdeMongo,Activo,FechaMigracion,FechaCreacion) VALUES(NEWID(),'sqlfirst:config:catalogo-ampliado-whatsapp-vencimiento','notification_config','{"id":"catalogo-ampliado-whatsapp-vencimiento","canal":"whatsapp","modulo":"catalogo_ampliado","evento":"DOCUMENTO_VENCIMIENTO","activo":true,"provider":"twilio","modo_envio":"real","template_codigo":"catalogo_ampliado_documento_vencimiento","permite_reintentos":true,"max_reintentos":3,"ventana_duplicidad_minutos":1440}',0,1,@now,@now);
 COMMIT TRANSACTION;
END TRY
BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK TRANSACTION; THROW; END CATCH;
