SET NOCOUNT ON;
SET XACT_ABORT ON;

IF DB_NAME() <> 'EDARSAHUB'
    THROW 51000, 'ABORT_WRONG_DATABASE', 1;

IF EXISTS (SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('dbo.Services_Providers'))
    THROW 51010, 'ABORT_DEPENDENT_SERVICES_OBJECTS_EXIST', 1;

IF OBJECT_ID('dbo.Services_Specialties','U') IS NOT NULL
AND EXISTS (SELECT 1 FROM dbo.Services_Specialties)
    THROW 51011, 'ABORT_ROLLBACK_DATA_PRESENT_SERVICES_SPECIALTIES', 1;

IF OBJECT_ID('dbo.Services_Professions','U') IS NOT NULL
AND EXISTS (SELECT 1 FROM dbo.Services_Professions)
    THROW 51012, 'ABORT_ROLLBACK_DATA_PRESENT_SERVICES_PROFESSIONS', 1;

BEGIN TRY
    BEGIN TRANSACTION;
    IF OBJECT_ID('dbo.Services_Specialties','U') IS NOT NULL DROP TABLE dbo.Services_Specialties;
    IF OBJECT_ID('dbo.Services_Professions','U') IS NOT NULL DROP TABLE dbo.Services_Professions;
    COMMIT;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
