SET NOCOUNT ON; SET XACT_ABORT ON;
BEGIN TRY
 BEGIN TRANSACTION;
 IF OBJECT_ID('dbo.Operativo_Notificaciones_Queue','U') IS NOT NULL AND NOT EXISTS(SELECT 1 FROM dbo.Operativo_Notificaciones_Queue) DROP TABLE dbo.Operativo_Notificaciones_Queue;
 DELETE rp FROM dbo.Sistema_RBAC_RolesPermisos rp JOIN dbo.Sistema_RBAC_Permisos p ON p.permiso_id=rp.permiso_id WHERE p.codigo IN (N'NOTIFICACIONES_VER',N'NOTIFICACIONES_CONFIGURAR',N'NOTIFICACIONES_ENVIAR');
 DELETE FROM dbo.Sistema_RBAC_Permisos WHERE codigo IN (N'NOTIFICACIONES_VER',N'NOTIFICACIONES_CONFIGURAR',N'NOTIFICACIONES_ENVIAR');
 COMMIT TRANSACTION;
END TRY
BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK TRANSACTION; THROW; END CATCH;
