#!/usr/bin/env bash
set -euo pipefail

STATE_DIR="/app/.git/mirror-sync"

ENABLE_FLAG="$STATE_DIR/ENABLED"
PERSISTENT_STOP="$STATE_DIR/STOP"

TEMP_STOP="/tmp/edarsahub-mirror-sync/STOP"

echo "===== EDARSAHUB MIRROR SYNC STATUS ====="

if [ -e "$PERSISTENT_STOP" ]; then
    echo "MIRROR_SYNC_ENABLED=NO"
    echo "EMERGENCY_STOP=ACTIVE"
    echo "REASON=PERSISTENT_STOP_FLAG"
elif [ -e "$TEMP_STOP" ]; then
    echo "MIRROR_SYNC_ENABLED=NO"
    echo "EMERGENCY_STOP=ACTIVE"
    echo "REASON=TEMPORARY_STOP_FLAG"
elif [ ! -e "$ENABLE_FLAG" ]; then
    echo "MIRROR_SYNC_ENABLED=NO"
    echo "EMERGENCY_STOP=INACTIVE"
    echo "REASON=PERSISTENT_ENABLE_ABSENT"
else
    echo "MIRROR_SYNC_ENABLED=YES"
    echo "EMERGENCY_STOP=INACTIVE"
    echo "REASON=AUTHORIZED"
fi

echo
echo "ENABLE_FLAG=$ENABLE_FLAG"
echo "PERSISTENT_STOP_FLAG=$PERSISTENT_STOP"
echo "TEMPORARY_STOP_FLAG=$TEMP_STOP"
