-- Data export for Usuario_Roles
-- Generated: 2026-06-03T00:43:18.723822
-- Total records: 21, Exported: 21

INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (1, N'ADMIN', N'Administrador', N'Acceso total del sistema', 1, 1, N'2026-04-06T17:46:08.838603', NULL, 0);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (2, N'GERENCIA', N'Gerencia', N'Rol gerencial con autorizaciones', 1, 1, N'2026-04-06T17:46:08.869857', NULL, 0);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (3, N'COMPRAS', N'Compras', N'Operador de compras', 1, 1, N'2026-04-06T17:46:08.916737', NULL, 0);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (4, N'VENTAS', N'Ventas', N'Operador de ventas', 1, 1, N'2026-04-06T17:46:09.010496', NULL, 0);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (5, N'TESORERIA', N'Tesoreria', N'Operador de pagos y tesoreria', 1, 1, N'2026-04-06T17:46:09.094862', NULL, 0);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (6, N'SUPERADMIN', N'SuperAdministrador', N'Acceso total al sistema', 1, 1, N'2026-05-13T18:50:10.655996', NULL, 100);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (7, N'SUPERVISOR', N'Supervisor', N'Supervisión de operaciones', 0, 1, N'2026-05-13T18:50:10.766645', NULL, 50);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (8, N'USUARIO', N'Usuario', N'Usuario estándar', 0, 1, N'2026-05-13T18:50:10.862651', NULL, 10);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (9, N'VISOR', N'Visor', N'Solo lectura', 0, 1, N'2026-05-13T18:50:10.956413', NULL, 5);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (10, N'DIRECCION', N'Dirección', N'Nivel dirección - autoriza montos altos y reversas', 1, 1, N'2026-05-14T12:59:52.506666', NULL, 80);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (11, N'GERENTE_OPS', N'Gerente Operaciones', N'Gerente de operaciones - autoriza y aplica cargos', 1, 1, N'2026-05-14T12:59:52.540000', NULL, 60);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (12, N'OPERADOR', N'Operador', N'Operador - ejecuta tareas y registra información', 1, 1, N'2026-05-14T12:59:52.570000', NULL, 20);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (13, N'AUDITOR', N'Auditor', N'Auditor - solo lectura para fiscalización', 1, 1, N'2026-05-14T12:59:52.603333', NULL, 30);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (14, N'CRM_ADMIN', N'CRM_Administrador', N'Acceso total al módulo CRM Comercial, pipelines y reportes globales', 0, 1, N'2026-05-28T22:44:56.305987', NULL, 90);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (15, N'CRM_EJEC', N'CRM_Ejecutivo', N'Acceso operativo al CRM: gestión de leads, cuentas propias, oportunidades y remisiones', 0, 1, N'2026-05-28T22:44:56.354146', NULL, 50);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (16, N'CRM_AUDIT', N'CRM_Auditor', N'Acceso de solo lectura a KPIs, métricas de cumplimiento y auditoría de solicitudes de alta', 0, 1, N'2026-05-28T22:44:56.386710', NULL, 70);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (17, N'ADMIN_COMERCIAL', N'Administrador Comercial', N'Administración completa del módulo comercial: KPIs, reportes, configuración de dashboards.', 0, 1, N'2026-06-02T10:42:45.727448', NULL, 85);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (18, N'GERENTE_UNIDAD', N'Gerente de Unidad', N'Gerente de unidad de negocio: acceso a métricas de su(s) unidad(es) asignada(s).', 0, 1, N'2026-06-02T10:42:45.727448', NULL, 55);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (19, N'ANALISTA_COMERCIAL', N'Analista Comercial', N'Analista de datos comerciales: consulta y exportación de métricas y reportes.', 0, 1, N'2026-06-02T10:42:45.727448', NULL, 40);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (20, N'VISOR_COMERCIAL', N'Visor Comercial', N'Solo lectura de métricas comerciales. Sin exportación ni configuración.', 0, 1, N'2026-06-02T10:42:45.727448', NULL, 10);
INSERT INTO [Usuario_Roles] ([RolID], [CodigoRol], [NombreRol], [Descripcion], [EsRolSistema], [Activo], [FechaAlta], [FechaModificacion], [NivelJerarquia]) VALUES (21, N'CONFIGURADOR_COMERCIAL', N'Configurador Comercial', N'Configuración y gestión operativa del portal de inteligencia comercial.', 0, 1, N'2026-06-02T10:42:45.727448', NULL, 45);
